name: Check Unity Personal License

on:
  workflow_dispatch:

jobs:
  activation:
    name: Activate Unity Personal
    runs-on: ubuntu-latest
    steps:
      - name: Activate Unity Personal license
        uses: buildalon/activate-unity-license@v2.2.2
        with:
          license: Personal
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}
          license-version: 6.x

      - name: Verify Unity license
        run: |
          echo "Unity Personal license activation completed successfully."
